### ISSUE TITLE
Cycling dependencies reported as AM_UNBOUND

### ISSUE THREAD

**Issue by jimon** [starwing/amoeba#10]
I'm trying make a layout system for games and amoeba is really looking very nice for this role (C interface, small one header lib 👍 ), while I was doing simple layouts everything was fine, but when I moved to a grid layout I noticed constants asserts. After a few days of digging through my constraint generation code I started to suspect some issues with amoeba itself, and unfortunately it might be a case.

So a specific of grid layout is that whole grid cannot be smaller than min size of every cell, yet every cell depends on size of whole grid (flexible cells), this kinda creates cycling dependencies, and a whole strong point of cassowary algorithm is to circumvent around cycling dependencies.

Minimal repro case that I've figured out would be va = vb = vc = vd = va, last constraint is reported as unbound.

	am_Solver * solver = am_newsolver(NULL, NULL);

	am_Variable * va = am_newvariable(solver);
	am_Variable * vb = am_newvariable(solver);
	am_Variable * vc = am_newvariable(solver);
	am_Variable * vd = am_newvariable(solver);

	int ret = 0;

	am_addedit(va, AM_STRONG);

	// vb == va
	{
		ret = 0;
		am_Constraint * c = am_newconstraint(solver, AM_REQUIRED);
		ret |= am_addterm(c, vb, 1.0);
		ret |= am_setrelation(c, AM_EQUAL);
		ret |= am_addterm(c, va, 1.0);
		ret |= am_add(c);
		assert(ret == AM_OK);
	}

	// vb == vc
	{
		ret = 0;
		am_Constraint * c = am_newconstraint(solver, AM_REQUIRED);
		ret |= am_addterm(c, vb, 1.0);
		ret |= am_setrelation(c, AM_EQUAL);
		ret |= am_addterm(c, vc, 1.0);
		ret |= am_add(c);
		assert(ret == AM_OK);
	}

	// vc == vd
	{
		ret = 0;
		am_Constraint * c = am_newconstraint(solver, AM_REQUIRED);
		ret |= am_addterm(c, vc, 1.0);
		ret |= am_setrelation(c, AM_EQUAL);
		ret |= am_addterm(c, vd, 1.0);
		ret |= am_add(c);
		assert(ret == AM_OK);
	}

	// vd == va
	{
		ret = 0;
		am_Constraint * c = am_newconstraint(solver, AM_REQUIRED);
		ret |= am_addterm(c, vd, 1.0);
		ret |= am_setrelation(c, AM_EQUAL);
		ret |= am_addterm(c, va, 1.0);
		ret |= am_add(c);
		assert(ret == AM_OK); // asserts here
	}

Similar thing implemented with https://github.com/nucleic/kiwi works, so either I'm missing something or is it really a bug? I would love to use this implementation :)

PS. This is how it looks with kiwi (used from python):

	from kiwisolver import Solver, Variable
	
	s = Solver()
	
	a = Variable('a')
	b = Variable('b')
	c = Variable('c')
	d = Variable('d')
	
	s.addEditVariable(a, 'strong')
	
	s.addConstraint(a == b)
	s.addConstraint(b == c)
	s.addConstraint(c == d)
	s.addConstraint(a == d)
	
	s.suggestValue(a, 2)
	s.updateVariables()
	
	print(a.value()) # all variables are 2
	print(b.value())
	print(c.value())
	print(d.value())

**Comment by starwing** [comment]
sorry about late reply, I'm busy with work these months :(

I will look into this when I have time, pull request welcome, any way :-)

**Comment by starwing** [comment]
I have submit a new commit, could you try whether the issue is solved?

**Comment by jimon** [comment]
@starwing hey, it works :) Thanks!

PS. I implemented all heavy lifting with kiwi during this time, so now it was easy to swap constraint solvers after everything else was done already. Here are some numbers that might be interesting: https://gist.github.com/jimon/d035dc3d1cc11e1deb6703a9bd73a4db my current UI contains 
247 widgets 1882 relations and on this set I get this performance:
- kiwi took 0.2433 ms
- amoeba took 0.4539 ms

Not bad indeed 👍 !

**Comment by starwing** [comment]
Thanks for numbers, I will use valgrind try to improve the performance when I have time :)
