### ISSUE TITLE
Assertion in am_dual_optimize() with valid constraint set

### ISSUE THREAD

**Issue by joshs6502** [starwing/amoeba#7]
I am using amoeba for a GUI framework, and I'm very happy with it.  But there is one particular case that is failing for me.

The scenario is a splitter view that has left and right child views and a splitter bar that can be dragged left or right.  The bar is constrained to always remain fully visible within the splitter view.  The right child may have various hierarchical constraints, but its right edge is always constrained at or beyond the right edge of the splitter view.  The left child has a fixed width of 256, but its left edge is unconstrained.  (The splitter, left child, splitter bar, and right child each constrain their right edge to their left edge plus their width.)

The left edge of the splitter bar is the only thing that I change, and I do that with `am_suggest(splitter_bar_l, pos)`.

Perhaps this is user error or perhaps I am missing something, but as far as I can tell, my constraints are entirely feasible.

In the attached code, if the `#if 0` in line 75 is replaced by `#if 1`, then the `(enter.id != 0)` assertion in `am_dual_optimize()` fails.  I do not believe it should fail.

With `#if 0` in line 75, I avoid the assertion failure, but amoeba insists on holding the left edge of the left child equal to zero instead of letting it equal the right edge minus 256.  That should not happen because as I mentioned above, the left edge is unconstrained, apart from being offset from the right edge.

Can you help me understand what I am doing wrong, or how I should approach this problem?  My actual scenario is more complex because the child views may contain all kinds of internal constraints, but the code that follows demonstrates the problem.

	#include <stdio.h>
	#include <stdarg.h>

	#define AM_IMPLEMENTATION
	#include "amoeba.h"
	#define END 0

	am_Constraint* new_constraint(am_Solver* in_solver, double in_strength, am_Variable* in_term1,
		double in_factor1, int in_relation, double in_constant, ...) {
		int result;
		va_list argp;
		am_Constraint* c;
		assert(in_solver && in_term1);
		c = am_newconstraint(in_solver, in_strength ? in_strength : AM_REQUIRED);
		if(!c) return 0;
		am_addterm(c, in_term1, in_factor1);
		am_setrelation(c, in_relation);
		if(in_constant) am_addconstant(c, in_constant);
		va_start(argp, in_constant);
		while(1) {
			am_Variable* va_term = va_arg(argp, am_Variable*);
			double va_factor = va_arg(argp, double);
			if(va_term == 0) break;
			am_addterm(c, va_term, va_factor);
		}
		va_end(argp);
		result = am_add(c);
		assert(result == AM_OK);
		return c;
	}

	int main(int argc, const char * argv[]) {

		double delta = 0;
		double pos;
		am_Solver* solver = am_newsolver(0, NULL);
		am_Variable* splitter_l = am_newvariable(solver);
		am_Variable* splitter_w = am_newvariable(solver);
		am_Variable* splitter_r = am_newvariable(solver);
		am_Variable* left_child_l = am_newvariable(solver);
		am_Variable* left_child_w = am_newvariable(solver);
		am_Variable* left_child_r = am_newvariable(solver);
		am_Variable* splitter_bar_l = am_newvariable(solver);
		am_Variable* splitter_bar_w = am_newvariable(solver);
		am_Variable* splitter_bar_r = am_newvariable(solver);
		am_Variable* right_child_l = am_newvariable(solver);
		am_Variable* right_child_w = am_newvariable(solver);
		am_Variable* right_child_r = am_newvariable(solver);
		/* splitter_r = splitter_l + splitter_w */
		/* left_child_r = left_child_l + left_child_w */
		/* splitter_bar_r = splitter_bar_l + splitter_bar_w */
		/* right_child_r = right_child_l + right_child_w */
		am_Constraint* c1 = new_constraint(solver, AM_REQUIRED, splitter_r, 1.0, AM_EQUAL, 0.0,
			splitter_l, 1.0, splitter_w, 1.0, END);
		am_Constraint* c2 = new_constraint(solver, AM_REQUIRED, left_child_r, 1.0, AM_EQUAL, 0.0,
			left_child_l, 1.0, left_child_w, 1.0, END);
		am_Constraint* c3 = new_constraint(solver, AM_REQUIRED, splitter_bar_r, 1.0, AM_EQUAL, 0.0,
			splitter_bar_l, 1.0, splitter_bar_w, 1.0, END);
		am_Constraint* c4 = new_constraint(solver, AM_REQUIRED, right_child_r, 1.0, AM_EQUAL, 0.0,
			right_child_l, 1.0, right_child_w, 1.0, END);
		/* splitter_bar_w = 6 */
		/* splitter_bar_l >= splitter_l + delta */
		/* splitter_bar_r <= splitter_r - delta */
		/* left_child_r = splitter_bar_l */
		/* right_child_l = splitter_bar_r */
		am_Constraint* c5 = new_constraint(solver, AM_REQUIRED, splitter_bar_w, 1.0, AM_EQUAL, 6.0, END);
		am_Constraint* c6 = new_constraint(solver, AM_REQUIRED, splitter_bar_l, 1.0, AM_GREATEQUAL,
			delta, splitter_l, 1.0, END);
		am_Constraint* c7 = new_constraint(solver, AM_REQUIRED, splitter_bar_r, 1.0, AM_LESSEQUAL,
			-delta, splitter_r, 1.0, END);
		am_Constraint* c8 = new_constraint(solver, AM_REQUIRED, left_child_r, 1.0, AM_EQUAL, 0.0,
			splitter_bar_l, 1.0, END);
		am_Constraint* c9 = new_constraint(solver, AM_REQUIRED, right_child_l, 1.0, AM_EQUAL, 0.0,
			splitter_bar_r, 1.0, END);
	#if 0
		/* This should be valid but fails the (enter.id != 0) assertion in am_dual_optimize() */
		int strength1 = AM_REQUIRED;
		int strength2 = AM_REQUIRED;
		int width = 76;
	#else
		/* This mostly works, but still insists on forcing left_child_l = 0 which it should not */
		int strength1 = AM_STRONG;
		int strength2 = AM_WEAK;
		int width = 76;
	#endif
		/* right_child_r >= splitter_r + 1 */
		/* left_child_w = 256 */
		am_Constraint* c10 = new_constraint(solver, strength1, right_child_r, 1.0, AM_GREATEQUAL, 1.0,
			splitter_r, 1.0, END);
		am_Constraint* c11 = new_constraint(solver, strength2, left_child_w, 1.0, AM_EQUAL, 256.0, END);
		/* splitter_l = 0 */
		/* splitter_r = 76 */
		am_Constraint* c12 = new_constraint(solver, AM_REQUIRED, splitter_l, 1.0, AM_EQUAL, 0.0, END);
		am_Constraint* c13 = new_constraint(solver, AM_REQUIRED, splitter_r, 1.0, AM_EQUAL, width, END);

		for(pos = -10; pos < 86; pos++) {
			am_suggest(splitter_bar_l, pos);
			printf("pos: %4g | ", pos);
			printf("splitter_l l=%2g, w=%2g, r=%2g | ", am_value(splitter_l),
				am_value(splitter_w), am_value(splitter_r));
			printf("left_child_l l=%2g, w=%2g, r=%2g | ", am_value(left_child_l),
				am_value(left_child_w), am_value(left_child_r));
			printf("splitter_bar_l l=%2g, w=%2g, r=%2g | ", am_value(splitter_bar_l),
				am_value(splitter_bar_w), am_value(splitter_bar_r));
			printf("right_child_l l=%2g, w=%2g, r=%2g | ", am_value(right_child_l),
				am_value(right_child_w), am_value(right_child_r));
			printf("\n");
		}

		(void) c1; (void) c2; (void) c3; (void) c4; (void) c5; (void) c6; (void) c7; (void) c8;
		(void) c9; (void) c10; (void) c11; (void) c12; (void) c13;
		return 0;
	}

**Comment by starwing** [comment]
hi, thanks for using it :-)

I will look into this~

**Comment by starwing** [comment]
I found a glitch in `am_suggest()` and fix it, now the test will not crashed, you could try the git HEAD. if have any other issue, welcome to re-open this issue, Thanks for report it :)

**Comment by joshs6502** [comment]
Thank you.  But when I run the sample code provided above, it still fails for me (when line 75 is "#if 1" instead of "if 0").

**Comment by starwing** [comment]
Okay, I made a new commit, you could try again. Sorry for my fault :(

**Comment by joshs6502** [comment]
Thank you.  That fixed my problem.
